---
<<: !include ../common/base.yaml
<<: !include ../common/time.yaml

esphome:
  name: ${id}
  platform: ESP8266
  board: esp8285

status_led:
  pin:
    number: GPIO2
    inverted: yes

binary_sensor:
  - !include ../common/binary_sensor/status.yaml

  - platform: gpio
    id: button
    name: ${name} Button
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: yes
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    id: relay
    name: ${name} Relay
    icon: mdi:power-socket-uk
    pin: GPIO15

sensor:
  - !include ../common/sensor/uptime.yaml
  - !include ../common/sensor/wifi_signal.yaml
  
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: yes
    cf_pin: GPIO5
    cf1_pin: GPIO14
    current_resistor: 0.00221
    voltage_divider: 871
    current:
      id: current
      name: ${name} Current
      icon: mdi:current-ac
    voltage:
      id: voltage
      name: ${name} Voltage
      icon: mdi:flash-circle
    power:
      id: power
      name: ${name} Power
      icon: mdi:flash-outline

  - platform: total_daily_energy
    id: daily_energy
    name: ${name} Power Today
    power_id: power
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh