---
<<: !include logger.yaml
<<: !include wifi.yaml
<<: !include api.yaml
<<: !include ota.yaml
<<: !include web_server.yaml

<<: !include binary_sensors.yaml
<<: !include sensors.yaml
<<: !include text_sensors.yaml